//! PDF report generation using genpdf

use genpdf::elements::{Break, LinearLayout, Paragraph, TableLayout};
use genpdf::style::Style;
use genpdf::{Alignment, Document, Element, Margins, SimplePageDecorator};
use protectinator_data::{StoredFinding, StoredScan};

/// Generate a PDF report from scan data
///
/// Returns the raw PDF bytes.
pub fn generate_pdf_report(
    scan: &StoredScan,
    findings: &[StoredFinding],
) -> Result<Vec<u8>, String> {
    // Try standard font paths
    let font_family = genpdf::fonts::from_files(
        "/usr/share/fonts/truetype/liberation",
        "LiberationSans",
        None,
    )
    .or_else(|_| {
        genpdf::fonts::from_files("/usr/share/fonts/truetype/dejavu", "DejaVuSans", None)
    })
    .or_else(|_| genpdf::fonts::from_files("/usr/share/fonts/TTF", "DejaVuSans", None))
    .map_err(|e| format!("No fonts available for PDF generation: {}", e))?;

    let mut doc = Document::new(font_family);
    doc.set_title("Protectinator Security Scan Report");

    let mut decorator = SimplePageDecorator::new();
    decorator.set_margins(Margins::trbl(15, 15, 15, 15));
    doc.set_page_decorator(decorator);

    // === Title ===
    doc.push(
        Paragraph::new("Protectinator Security Scan Report")
            .aligned(Alignment::Center)
            .styled(Style::new().bold().with_font_size(18)),
    );
    doc.push(Break::new(1));

    // === Scan Info ===
    doc.push(Paragraph::new(format!("Host: {}", scan.repo_path))
        .styled(Style::new().with_font_size(11)));
    doc.push(Paragraph::new(format!("Scan Date: {}", scan.scanned_at))
        .styled(Style::new().with_font_size(11)));
    doc.push(Paragraph::new(format!("Total Findings: {}", scan.total_findings))
        .styled(Style::new().with_font_size(11)));
    doc.push(Break::new(1));

    // === Severity Summary ===
    doc.push(Paragraph::new("Severity Summary")
        .styled(Style::new().bold().with_font_size(14)));
    doc.push(Break::new(0.5));

    let mut summary_table = TableLayout::new(vec![1, 1, 1, 1, 1]);
    summary_table.set_cell_decorator(genpdf::elements::FrameCellDecorator::new(true, true, false));

    summary_table
        .row()
        .element(cell("Critical", true))
        .element(cell("High", true))
        .element(cell("Medium", true))
        .element(cell("Low", true))
        .element(cell("Info", true))
        .push()
        .map_err(|e| format!("Table error: {}", e))?;

    summary_table
        .row()
        .element(cell(&scan.critical.to_string(), false))
        .element(cell(&scan.high.to_string(), false))
        .element(cell(&scan.medium.to_string(), false))
        .element(cell(&scan.low.to_string(), false))
        .element(cell(&scan.info.to_string(), false))
        .push()
        .map_err(|e| format!("Table error: {}", e))?;

    doc.push(summary_table);
    doc.push(Break::new(1));

    // === Findings by Severity ===
    for severity in &["Critical", "High", "Medium", "Low", "Info"] {
        let sev_findings: Vec<&StoredFinding> = findings
            .iter()
            .filter(|f| f.severity == *severity)
            .collect();

        if sev_findings.is_empty() {
            continue;
        }

        doc.push(Paragraph::new(format!("{} Findings ({})", severity, sev_findings.len()))
            .styled(Style::new().bold().with_font_size(12)));
        doc.push(Break::new(0.3));

        for finding in sev_findings {
            let mut layout = LinearLayout::vertical();

            layout.push(Paragraph::new(&finding.title)
                .styled(Style::new().bold().with_font_size(10)));

            if let Some(ref resource) = finding.resource {
                layout.push(Paragraph::new(format!("Resource: {}", resource))
                    .styled(Style::new().with_font_size(9).italic()));
            }

            if let Some(ref category) = finding.check_category {
                layout.push(Paragraph::new(format!("Category: {}", category))
                    .styled(Style::new().with_font_size(9)));
            }

            if let Some(ref remediation) = finding.remediation {
                layout.push(Paragraph::new(format!("Remediation: {}", remediation))
                    .styled(Style::new().with_font_size(9)));
            }

            doc.push(layout);
            doc.push(Break::new(0.3));
        }

        doc.push(Break::new(0.5));
    }

    // === Footer ===
    doc.push(Break::new(1));
    doc.push(
        Paragraph::new(format!(
            "Generated by Protectinator on {}",
            chrono::Utc::now().format("%Y-%m-%d %H:%M:%S UTC")
        ))
        .aligned(Alignment::Center)
        .styled(Style::new().with_font_size(8).italic()),
    );

    // Render to bytes
    let mut buf = Vec::new();
    doc.render(&mut buf)
        .map_err(|e| format!("Failed to render PDF: {}", e))?;

    Ok(buf)
}

fn cell(text: &str, bold: bool) -> impl Element {
    let style = if bold {
        Style::new().bold().with_font_size(10)
    } else {
        Style::new().with_font_size(10)
    };
    Paragraph::new(text).aligned(Alignment::Center).styled(style)
}
