//! Cargo.lock parser
//!
//! Parses Rust's Cargo.lock files (TOML format) into normalized package entries.

use crate::types::{Ecosystem, PackageEntry};
use serde::Deserialize;

#[derive(Deserialize)]
struct CargoLockFile {
    #[serde(default)]
    package: Vec<CargoPackage>,
}

#[derive(Deserialize)]
struct CargoPackage {
    name: String,
    version: String,
    source: Option<String>,
    checksum: Option<String>,
}

/// Parse a Cargo.lock file content into package entries.
///
/// Filters out local path dependencies (source starting with `path+`)
/// and maps remaining packages to `PackageEntry` with `Ecosystem::CratesIo`.
pub fn parse(content: &str) -> Vec<PackageEntry> {
    let lock_file: CargoLockFile = match toml::from_str(content) {
        Ok(lf) => lf,
        Err(e) => {
            tracing::warn!("Failed to parse Cargo.lock as TOML: {}", e);
            return Vec::new();
        }
    };

    lock_file
        .package
        .into_iter()
        .filter(|pkg| {
            // Skip local path dependencies
            if let Some(ref source) = pkg.source {
                !source.starts_with("path+")
            } else {
                // Packages without a source field are typically the workspace root
                false
            }
        })
        .map(|pkg| PackageEntry {
            name: pkg.name,
            version: pkg.version,
            ecosystem: Ecosystem::CratesIo,
            source_url: pkg.source,
            checksum: pkg.checksum,
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE_CARGO_LOCK: &str = r#"
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "my-app"
version = "0.1.0"

[[package]]
name = "serde"
version = "1.0.197"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "3fb1c873e1b9b056a4dc4c0c198b24c3ffa059243875552b2bd0933b1aee4ce2"

[[package]]
name = "serde_json"
version = "1.0.114"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "c5363b3bbbf7290e6ea54b7007035a8de7f8bc166454a28e0b18e6cab5658738"
dependencies = [
 "serde",
]

[[package]]
name = "local-crate"
version = "0.1.0"
source = "path+file:///home/user/projects/local-crate"
"#;

    #[test]
    fn test_parse_cargo_lock() {
        let packages = parse(SAMPLE_CARGO_LOCK);
        assert_eq!(packages.len(), 2);

        let serde = packages.iter().find(|p| p.name == "serde").unwrap();
        assert_eq!(serde.version, "1.0.197");
        assert_eq!(serde.ecosystem, Ecosystem::CratesIo);
        assert!(serde
            .source_url
            .as_ref()
            .unwrap()
            .contains("crates.io-index"));
        assert!(serde.checksum.is_some());

        let serde_json = packages.iter().find(|p| p.name == "serde_json").unwrap();
        assert_eq!(serde_json.version, "1.0.114");
    }

    #[test]
    fn test_filters_path_dependencies() {
        let packages = parse(SAMPLE_CARGO_LOCK);
        assert!(
            packages.iter().all(|p| p.name != "local-crate"),
            "path dependencies should be filtered out"
        );
        assert!(
            packages.iter().all(|p| p.name != "my-app"),
            "workspace root (no source) should be filtered out"
        );
    }

    #[test]
    fn test_parse_empty_cargo_lock() {
        let content = r#"
version = 4
"#;
        let packages = parse(content);
        assert!(packages.is_empty());
    }

    #[test]
    fn test_parse_malformed_toml() {
        let packages = parse("this is not valid toml {{{");
        assert!(packages.is_empty());
    }
}
