//! yarn.lock (v1) parser
//!
//! Parses Yarn v1 lock files (custom format) into normalized package entries.
//! The format is line-based with indentation-significant blocks.

use crate::types::{Ecosystem, PackageEntry};

/// Parse a yarn.lock (v1) file content into package entries.
///
/// Handles both regular and scoped packages (e.g. `@scope/name@^1.0.0`).
/// Skips entries where the version cannot be determined.
pub fn parse(content: &str) -> Vec<PackageEntry> {
    let mut packages = Vec::new();
    let mut current_name: Option<String> = None;
    let mut current_version: Option<String> = None;
    let mut current_resolved: Option<String> = None;
    let mut current_integrity: Option<String> = None;

    for line in content.lines() {
        // Skip comments and empty lines
        if line.starts_with('#') || line.trim().is_empty() {
            continue;
        }

        // Package header: non-indented line ending with ':'
        if !line.starts_with(' ') && !line.starts_with('\t') && line.ends_with(':') {
            // Flush previous package if we have one
            if let (Some(name), Some(version)) = (current_name.take(), current_version.take()) {
                packages.push(PackageEntry {
                    name,
                    version,
                    ecosystem: Ecosystem::Npm,
                    source_url: current_resolved.take(),
                    checksum: current_integrity.take(),
                });
            } else {
                current_version = None;
                current_resolved = None;
                current_integrity = None;
            }

            // Extract package name from header
            // Header can be: `package@^1.0.0:` or `"@scope/package@^1.0.0":`
            // or multiple entries: `package@^1.0.0, package@~1.0.0:`
            let header = line.trim_end_matches(':').trim();
            // Take the first entry if comma-separated
            let first_entry = header.split(',').next().unwrap_or(header).trim();
            // Remove surrounding quotes
            let entry = first_entry.trim_matches('"');

            current_name = extract_package_name(entry);
            continue;
        }

        // Indented lines: version, resolved, integrity
        let trimmed = line.trim();
        if trimmed.starts_with("version ") {
            current_version = extract_quoted_value(trimmed, "version ");
        } else if trimmed.starts_with("resolved ") {
            current_resolved = extract_quoted_value(trimmed, "resolved ");
        } else if trimmed.starts_with("integrity ") {
            // integrity values may or may not be quoted
            let value = trimmed.trim_start_matches("integrity ").trim_matches('"');
            if !value.is_empty() {
                current_integrity = Some(value.to_string());
            }
        }
    }

    // Flush the last package
    if let (Some(name), Some(version)) = (current_name, current_version) {
        packages.push(PackageEntry {
            name,
            version,
            ecosystem: Ecosystem::Npm,
            source_url: current_resolved,
            checksum: current_integrity,
        });
    }

    packages
}

/// Extract package name from an entry like `@scope/name@^1.0.0` or `name@^1.0.0`.
///
/// The name is everything before the last `@` (excluding the leading `@` for scoped packages).
fn extract_package_name(entry: &str) -> Option<String> {
    // Handle scoped packages: @scope/name@version
    // Find the last '@' that is not at position 0
    let search_start = if entry.starts_with('@') { 1 } else { 0 };
    let rest = &entry[search_start..];
    match rest.rfind('@') {
        Some(pos) => {
            let name = &entry[..search_start + pos];
            if name.is_empty() {
                None
            } else {
                Some(name.to_string())
            }
        }
        None => {
            tracing::warn!("Could not extract package name from yarn.lock entry: {}", entry);
            None
        }
    }
}

/// Extract a quoted value from a line like `version "1.2.3"`.
fn extract_quoted_value(line: &str, prefix: &str) -> Option<String> {
    let value = line.trim_start_matches(prefix).trim().trim_matches('"');
    if value.is_empty() {
        None
    } else {
        Some(value.to_string())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE_YARN_LOCK: &str = r#"# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


accepts@~1.3.8:
  version "1.3.8"
  resolved "https://registry.yarnpkg.com/accepts/-/accepts-1.3.8.tgz#0bf0be125b67014adcb0b0921e62db7bffe16b2e"
  integrity sha512-PYAthTa2m2VKxuvSD3DPC/Gy+U+sOA1LAuT8mkmRuvw+NACSaeXEQ+NHcVF7rONl6qcaxV3Uuemwawk+7+SJLw==

"@babel/core@^7.0.0":
  version "7.24.0"
  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.24.0.tgz#a12e8f4d4b0"
  integrity sha512-fQAJbkl+abc123==

lodash@^4.17.21, lodash@~4.17.0:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#679591c564c3bffc"
"#;

    #[test]
    fn test_parse_yarn_lock() {
        let packages = parse(SAMPLE_YARN_LOCK);
        assert_eq!(packages.len(), 3);

        let accepts = packages.iter().find(|p| p.name == "accepts").unwrap();
        assert_eq!(accepts.version, "1.3.8");
        assert_eq!(accepts.ecosystem, Ecosystem::Npm);
        assert!(accepts.source_url.as_ref().unwrap().contains("registry.yarnpkg.com"));
        assert!(accepts.checksum.is_some());

        let babel = packages.iter().find(|p| p.name == "@babel/core").unwrap();
        assert_eq!(babel.version, "7.24.0");

        let lodash = packages.iter().find(|p| p.name == "lodash").unwrap();
        assert_eq!(lodash.version, "4.17.21");
        // lodash entry has no integrity line
        assert!(lodash.checksum.is_none());
    }

    #[test]
    fn test_scoped_package_name_extraction() {
        assert_eq!(
            extract_package_name("@babel/core@^7.0.0"),
            Some("@babel/core".to_string())
        );
        assert_eq!(
            extract_package_name("lodash@^4.17.21"),
            Some("lodash".to_string())
        );
        assert_eq!(
            extract_package_name("@types/node@>=10"),
            Some("@types/node".to_string())
        );
    }

    #[test]
    fn test_parse_empty_yarn_lock() {
        let content = r#"# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

"#;
        let packages = parse(content);
        assert!(packages.is_empty());
    }

    #[test]
    fn test_parse_malformed_entries() {
        // Entry without version line should be skipped
        let content = r#"
some-package@^1.0.0:
  resolved "https://example.com/some.tgz"

valid-package@^2.0.0:
  version "2.0.0"
  resolved "https://example.com/valid.tgz"
"#;
        let packages = parse(content);
        assert_eq!(packages.len(), 1);
        assert_eq!(packages[0].name, "valid-package");
    }
}
